a = [
    {
        "type": "recipe",
        "name": "uranium-rounds-magazine",
        "enabled": False,
        "energy_required": 10,
        "ingredients": {"piercing-rounds-magazine": 1, "uranium-238": 1},
        "result": "uranium-rounds-magazine",
    },
    {
        "type": "recipe",
        "name": "rocket",
        "enabled": False,
        "energy_required": 8,
        "ingredients": {"electronic-circuit": 1, "explosives": 1, "iron-plate": 2},
        "result": "rocket",
    },
    {
        "type": "recipe",
        "name": "explosive-rocket",
        "enabled": False,
        "energy_required": 8,
        "ingredients": {"rocket": 1, "explosives": 2},
        "result": "explosive-rocket",
    },
    {
        "type": "recipe",
        "name": "atomic-bomb",
        "enabled": False,
        "energy_required": 50,
        "ingredients": {"rocket-control-unit": 10, "explosives": 10, "uranium-235": 30},
        "result": "atomic-bomb",
    },
    {
        "type": "recipe",
        "name": "piercing-shotgun-shell",
        "enabled": False,
        "energy_required": 8,
        "ingredients": {"shotgun-shell": 2, "copper-plate": 5, "steel-plate": 2},
        "result": "piercing-shotgun-shell",
    },
    {
        "type": "recipe",
        "name": "railgun-dart",
        "enabled": False,
        "energy_required": 8,
        "ingredients": {"steel-plate": 5, "electronic-circuit": 5},
        "result": "railgun-dart",
    },
    {
        "type": "recipe",
        "name": "cannon-shell",
        "normal": {
            "enabled": False,
            "energy_required": 8,
            "ingredients": {"steel-plate": 2, "plastic-bar": 2, "explosives": 1},
            "result": "cannon-shell",
        },
        "expensive": {
            "enabled": False,
            "energy_required": 8,
            "ingredients": {"steel-plate": 4, "plastic-bar": 4, "explosives": 1},
            "result": "cannon-shell",
        },
    },
    {
        "type": "recipe",
        "name": "explosive-cannon-shell",
        "normal": {
            "enabled": False,
            "energy_required": 8,
            "ingredients": {"steel-plate": 2, "plastic-bar": 2, "explosives": 2},
            "result": "explosive-cannon-shell",
        },
        "expensive": {
            "enabled": False,
            "energy_required": 8,
            "ingredients": {"steel-plate": 4, "plastic-bar": 4, "explosives": 2},
            "result": "explosive-cannon-shell",
        },
    },
    {
        "type": "recipe",
        "name": "uranium-cannon-shell",
        "enabled": False,
        "energy_required": 12,
        "ingredients": {"cannon-shell": 1, "uranium-238": 1},
        "result": "uranium-cannon-shell",
    },
    {
        "type": "recipe",
        "name": "explosive-uranium-cannon-shell",
        "enabled": False,
        "energy_required": 12,
        "ingredients": {"explosive-cannon-shell": 1, "uranium-238": 1},
        "result": "explosive-uranium-cannon-shell",
    },
    {
        "type": "recipe",
        "name": "artillery-shell",
        "enabled": False,
        "energy_required": 15,
        "ingredients": {"explosive-cannon-shell": 4, "radar": 1, "explosives": 8},
        "result": "artillery-shell",
    },
    {
        "type": "recipe",
        "name": "flamethrower-ammo",
        "category": "chemistry",
        "enabled": False,
        "energy_required": 6,
        "ingredients": {"steel-plate": 5, "crude-oil": 100},
        "result": "flamethrower-ammo",
        "crafting_machine_tint": {
            "primary": {"r": 1.000, "g": 0.735, "b": 0.643, "a": 1.000},
            "secondary": {"r": 0.749, "g": 0.557, "b": 0.490, "a": 1.000},
            "tertiary": {"r": 0.637, "g": 0.637, "b": 0.637, "a": 1.000},
            "quaternary": {"r": 0.283, "g": 0.283, "b": 0.283, "a": 1.000},
        },
    },
]
