a = [
    {
        "type": "recipe",
        "name": "poison-capsule",
        "enabled": False,
        "energy_required": 8,
        "ingredients": {"steel-plate": 3, "electronic-circuit": 3, "coal": 10},
        "result": "poison-capsule",
    },
    {
        "type": "recipe",
        "name": "slowdown-capsule",
        "enabled": False,
        "energy_required": 8,
        "ingredients": {"steel-plate": 2, "electronic-circuit": 2, "coal": 5},
        "result": "slowdown-capsule",
    },
    {
        "type": "recipe",
        "name": "cluster-grenade",
        "enabled": False,
        "energy_required": 8,
        "ingredients": {"grenade": 7, "explosives": 5, "steel-plate": 5},
        "result": "cluster-grenade",
    },
    {
        "type": "recipe",
        "name": "defender-capsule",
        "enabled": False,
        "energy_required": 8,
        "ingredients": {
            "piercing-rounds-magazine": 3,
            "electronic-circuit": 3,
            "iron-gear-wheel": 3,
        },
        "result": "defender-capsule",
    },
    {
        "type": "recipe",
        "name": "distractor-capsule",
        "enabled": False,
        "energy_required": 15,
        "ingredients": {"defender-capsule": 4, "advanced-circuit": 3},
        "result": "distractor-capsule",
    },
    {
        "type": "recipe",
        "name": "destroyer-capsule",
        "enabled": False,
        "energy_required": 15,
        "ingredients": {"distractor-capsule": 4, "speed-module": 1},
        "result": "destroyer-capsule",
    },
    {
        "type": "recipe",
        "name": "discharge-defense-remote",
        "enabled": False,
        "ingredients": {"electronic-circuit": 1},
        "result": "discharge-defense-remote",
    },
    {
        "type": "recipe",
        "name": "cliff-explosives",
        "enabled": False,
        "energy_required": 8,
        "ingredients": {"explosives": 10, "grenade": 1, "empty-barrel": 1},
        "result": "cliff-explosives",
    },
    {
        "type": "recipe",
        "name": "artillery-targeting-remote",
        "enabled": False,
        "ingredients": {"processing-unit": 1, "radar": 1},
        "result": "artillery-targeting-remote",
    },
]
