modules = [
    {
        "type": "recipe",
        "name": "speed-module",
        "enabled": False,
        "ingredients": {"advanced-circuit": 5, "electronic-circuit": 5},
        "energy_required": 15,
        "result": "speed-module",
    },
    {
        "type": "recipe",
        "name": "speed-module-2",
        "enabled": False,
        "ingredients": {"speed-module": 4, "advanced-circuit": 5, "processing-unit": 5},
        "energy_required": 30,
        "result": "speed-module-2",
    },
    {
        "type": "recipe",
        "name": "speed-module-3",
        "enabled": False,
        "ingredients": {
            "speed-module-2": 5,
            "advanced-circuit": 5,
            "processing-unit": 5,
        },
        "energy_required": 60,
        "result": "speed-module-3",
    },
    {
        "type": "recipe",
        "name": "productivity-module",
        "enabled": False,
        "ingredients": {"advanced-circuit": 5, "electronic-circuit": 5},
        "energy_required": 15,
        "result": "productivity-module",
    },
    {
        "type": "recipe",
        "name": "productivity-module-2",
        "enabled": False,
        "ingredients": {
            "productivity-module": 4,
            "advanced-circuit": 5,
            "processing-unit": 5,
        },
        "energy_required": 30,
        "result": "productivity-module-2",
    },
    {
        "type": "recipe",
        "name": "productivity-module-3",
        "enabled": False,
        "ingredients": {
            "productivity-module-2": 5,
            "advanced-circuit": 5,
            "processing-unit": 5,
        },
        "energy_required": 60,
        "result": "productivity-module-3",
    },
    {
        "type": "recipe",
        "name": "efficiency-module",
        "enabled": False,
        "ingredients": {"advanced-circuit": 5, "electronic-circuit": 5},
        "energy_required": 15,
        "result": "efficiency-module",
    },
    {
        "type": "recipe",
        "name": "efficiency-module-2",
        "enabled": False,
        "ingredients": {
            "efficiency-module": 4,
            "advanced-circuit": 5,
            "processing-unit": 5,
        },
        "energy_required": 30,
        "result": "efficiency-module-2",
    },
    {
        "type": "recipe",
        "name": "efficiency-module-3",
        "enabled": False,
        "ingredients": {
            "efficiency-module-2": 5,
            "advanced-circuit": 5,
            "processing-unit": 5,
        },
        "energy_required": 60,
        "result": "efficiency-module-3",
    },
]
