r = [
    {
        "type": "recipe",
        "name": "player-port",
        "enabled": False,
        "ingredients": {
            "electronic-circuit": 10,
            "iron-gear-wheel": 5,
            "iron-plate": 1,
        },
        "result": "player-port",
    },
    {
        "type": "recipe",
        "name": "fast-transport-belt",
        "enabled": False,
        "ingredients": {"iron-gear-wheel": 5, "transport-belt": 1},
        "result": "fast-transport-belt",
    },
    {
        "type": "recipe",
        "name": "express-transport-belt",
        "category": "crafting-with-fluid",
        "normal": {
            "enabled": False,
            "ingredients": {
                "iron-gear-wheel": 10,
                "fast-transport-belt": 1,
                "lubricant": 20,
            },
            "result": "express-transport-belt",
        },
        "expensive": {
            "enabled": False,
            "ingredients": {
                "iron-gear-wheel": 20,
                "fast-transport-belt": 1,
                "lubricant": 20,
            },
            "result": "express-transport-belt",
        },
    },
    {
        "type": "recipe",
        "name": "solar-panel",
        "energy_required": 10,
        "enabled": False,
        "ingredients": {"steel-plate": 5, "electronic-circuit": 15, "copper-plate": 5},
        "result": "solar-panel",
    },
    {
        "type": "recipe",
        "name": "assembling-machine-3",
        "enabled": False,
        "ingredients": {"speed-module": 4, "assembling-machine-2": 2},
        "result": "assembling-machine-3",
    },
    {
        "type": "recipe",
        "name": "tank",
        "normal": {
            "enabled": False,
            "energy_required": 5,
            "ingredients": {
                "engine-unit": 32,
                "steel-plate": 50,
                "iron-gear-wheel": 15,
                "advanced-circuit": 10,
            },
            "result": "tank",
        },
        "expensive": {
            "enabled": False,
            "energy_required": 8,
            "ingredients": {
                "engine-unit": 64,
                "steel-plate": 100,
                "iron-gear-wheel": 30,
                "advanced-circuit": 20,
            },
            "result": "tank",
        },
    },
    {
        "type": "recipe",
        "name": "rail",
        "enabled": False,
        "ingredients": {"stone": 1, "iron-stick": 1, "steel-plate": 1},
        "result": "rail",
        "result_count": 2,
    },
    {
        "type": "recipe",
        "name": "locomotive",
        "energy_required": 4,
        "enabled": False,
        "ingredients": {"engine-unit": 20, "electronic-circuit": 10, "steel-plate": 30},
        "result": "locomotive",
    },
    {
        "type": "recipe",
        "name": "cargo-wagon",
        "energy_required": 1,
        "enabled": False,
        "ingredients": {"iron-gear-wheel": 10, "iron-plate": 20, "steel-plate": 20},
        "result": "cargo-wagon",
    },
    {
        "type": "recipe",
        "name": "fluid-wagon",
        "enabled": False,
        "energy_required": 1.5,
        "ingredients": {
            "iron-gear-wheel": 10,
            "steel-plate": 16,
            "pipe": 8,
            "storage-tank": 1,
        },
        "result": "fluid-wagon",
    },
    {
        "type": "recipe",
        "name": "artillery-wagon",
        "energy_required": 4,
        "enabled": False,
        "ingredients": {
            "engine-unit": 64,
            "iron-gear-wheel": 10,
            "steel-plate": 40,
            "pipe": 16,
            "advanced-circuit": 20,
        },
        "result": "artillery-wagon",
    },
    {
        "type": "recipe",
        "name": "train-stop",
        "enabled": False,
        "ingredients": {
            "electronic-circuit": 5,
            "iron-plate": 6,
            "iron-stick": 6,
            "steel-plate": 3,
        },
        "result": "train-stop",
    },
    {
        "type": "recipe",
        "name": "rail-signal",
        "enabled": False,
        "ingredients": {"electronic-circuit": 1, "iron-plate": 5},
        "result": "rail-signal",
    },
    {
        "type": "recipe",
        "name": "rail-chain-signal",
        "enabled": False,
        "ingredients": {"electronic-circuit": 1, "iron-plate": 5},
        "result": "rail-chain-signal",
    },
    {
        "type": "recipe",
        "name": "heavy-armor",
        "enabled": False,
        "energy_required": 8,
        "ingredients": {"copper-plate": 100, "steel-plate": 50},
        "result": "heavy-armor",
    },
    {
        "type": "recipe",
        "name": "modular-armor",
        "enabled": False,
        "energy_required": 15,
        "ingredients": {"advanced-circuit": 30, "steel-plate": 50},
        "result": "modular-armor",
    },
    {
        "type": "recipe",
        "name": "power-armor",
        "enabled": False,
        "energy_required": 20,
        "ingredients": {
            "processing-unit": 40,
            "electric-engine-unit": 20,
            "steel-plate": 40,
        },
        "result": "power-armor",
        "requester_paste_multiplier": 1,
    },
    {
        "type": "recipe",
        "name": "power-armor-mk2",
        "enabled": False,
        "energy_required": 25,
        "ingredients": {
            "effectivity-module-2": 25,
            "speed-module-2": 25,
            "processing-unit": 60,
            "electric-engine-unit": 40,
            "low-density-structure": 30,
        },
        "result": "power-armor-mk2",
        "requester_paste_multiplier": 1,
    },
    {
        "type": "recipe",
        "name": "steel-chest",
        "enabled": False,
        "ingredients": {"steel-plate": 8},
        "result": "steel-chest",
    },
    {
        "type": "recipe",
        "name": "flamethrower",
        "enabled": False,
        "energy_required": 10,
        "ingredients": {"steel-plate": 5, "iron-gear-wheel": 10},
        "result": "flamethrower",
    },
    {
        "type": "recipe",
        "name": "land-mine",
        "enabled": False,
        "energy_required": 5,
        "ingredients": {"steel-plate": 1, "explosives": 2},
        "result": "land-mine",
        "result_count": 4,
    },
    {
        "type": "recipe",
        "name": "rocket-launcher",
        "enabled": False,
        "energy_required": 10,
        "ingredients": {"iron-plate": 5, "iron-gear-wheel": 5, "electronic-circuit": 5},
        "result": "rocket-launcher",
    },
    {
        "type": "recipe",
        "name": "combat-shotgun",
        "enabled": False,
        "energy_required": 10,
        "ingredients": {
            "steel-plate": 15,
            "iron-gear-wheel": 5,
            "copper-plate": 10,
            "wood": 10,
        },
        "result": "combat-shotgun",
    },
    {
        "type": "recipe",
        "name": "railgun",
        "enabled": False,
        "energy_required": 8,
        "ingredients": {
            "steel-plate": 15,
            "copper-plate": 15,
            "electronic-circuit": 10,
            "advanced-circuit": 5,
        },
        "result": "railgun",
    },
    {
        "type": "recipe",
        "name": "chemical-science-pack",
        "enabled": False,
        "energy_required": 24,
        "ingredients": {"engine-unit": 2, "advanced-circuit": 3, "sulfur": 1},
        "result_count": 2,
        "result": "chemical-science-pack",
    },
    {
        "type": "recipe",
        "name": "military-science-pack",
        "enabled": False,
        "energy_required": 10,
        "ingredients": {"piercing-rounds-magazine": 1, "grenade": 1, "stone-wall": 2},
        "result_count": 2,
        "result": "military-science-pack",
    },
    {
        "type": "recipe",
        "name": "production-science-pack",
        "enabled": False,
        "energy_required": 21,
        "ingredients": {"electric-furnace": 1, "productivity-module": 1, "rail": 30},
        "result_count": 3,
        "result": "production-science-pack",
    },
    {
        "type": "recipe",
        "name": "utility-science-pack",
        "enabled": False,
        "energy_required": 21,
        "ingredients": {
            "low-density-structure": 3,
            "processing-unit": 2,
            "flying-robot-frame": 1,
        },
        "result_count": 3,
        "result": "utility-science-pack",
    },
    {
        "type": "recipe",
        "name": "red-wire",
        "enabled": False,
        "ingredients": {"electronic-circuit": 1, "copper-cable": 1},
        "result": "red-wire",
    },
    {
        "type": "recipe",
        "name": "green-wire",
        "enabled": False,
        "ingredients": {"electronic-circuit": 1, "copper-cable": 1},
        "result": "green-wire",
    },
    {
        "type": "recipe",
        "name": "fast-underground-belt",
        "energy_required": 2,
        "enabled": False,
        "ingredients": {"iron-gear-wheel": 40, "underground-belt": 2},
        "result_count": 2,
        "result": "fast-underground-belt",
    },
    {
        "type": "recipe",
        "name": "express-underground-belt",
        "energy_required": 2,
        "category": "crafting-with-fluid",
        "enabled": False,
        "ingredients": {
            "iron-gear-wheel": 80,
            "fast-underground-belt": 2,
            "lubricant": 40,
        },
        "result_count": 2,
        "result": "express-underground-belt",
    },
    {
        "type": "recipe",
        "name": "fast-loader",
        "enabled": False,
        "energy_required": 3,
        "ingredients": {"fast-transport-belt": 5, "loader": 1},
        "result": "fast-loader",
    },
    {
        "type": "recipe",
        "name": "express-loader",
        "enabled": False,
        "energy_required": 10,
        "ingredients": {"express-transport-belt": 5, "fast-loader": 1},
        "result": "express-loader",
    },
    {
        "type": "recipe",
        "name": "fast-splitter",
        "enabled": False,
        "energy_required": 2,
        "ingredients": {"splitter": 1, "iron-gear-wheel": 10, "electronic-circuit": 10},
        "result": "fast-splitter",
    },
    {
        "type": "recipe",
        "name": "express-splitter",
        "category": "crafting-with-fluid",
        "enabled": False,
        "energy_required": 2,
        "ingredients": {
            "fast-splitter": 1,
            "iron-gear-wheel": 10,
            "advanced-circuit": 10,
            "lubricant": 80,
        },
        "result": "express-splitter",
    },
    {
        "type": "recipe",
        "name": "advanced-circuit",
        "normal": {
            "enabled": False,
            "energy_required": 6,
            "ingredients": {
                "electronic-circuit": 2,
                "plastic-bar": 2,
                "copper-cable": 4,
            },
            "result": "advanced-circuit",
        },
        "expensive": {
            "enabled": False,
            "energy_required": 6,
            "ingredients": {
                "electronic-circuit": 2,
                "plastic-bar": 4,
                "copper-cable": 8,
            },
            "result": "advanced-circuit",
        },
    },
    {
        "type": "recipe",
        "name": "processing-unit",
        "category": "crafting-with-fluid",
        "normal": {
            "enabled": False,
            "energy_required": 10,
            "ingredients": {
                "electronic-circuit": 20,
                "advanced-circuit": 2,
                "sulfuric-acid": 5,
            },
            "result": "processing-unit",
        },
        "expensive": {
            "enabled": False,
            "energy_required": 10,
            "ingredients": {
                "electronic-circuit": 20,
                "advanced-circuit": 2,
                "sulfuric-acid": 10,
            },
            "result": "processing-unit",
        },
    },
    {
        "type": "recipe",
        "name": "logistic-robot",
        "enabled": False,
        "ingredients": {"flying-robot-frame": 1, "advanced-circuit": 2},
        "result": "logistic-robot",
    },
    {
        "type": "recipe",
        "name": "construction-robot",
        "enabled": False,
        "ingredients": {"flying-robot-frame": 1, "electronic-circuit": 2},
        "result": "construction-robot",
    },
    {
        "type": "recipe",
        "name": "logistic-chest-passive-provider",
        "enabled": False,
        "ingredients": {
            "steel-chest": 1,
            "electronic-circuit": 3,
            "advanced-circuit": 1,
        },
        "result": "logistic-chest-passive-provider",
    },
    {
        "type": "recipe",
        "name": "logistic-chest-active-provider",
        "enabled": False,
        "ingredients": {
            "steel-chest": 1,
            "electronic-circuit": 3,
            "advanced-circuit": 1,
        },
        "result": "logistic-chest-active-provider",
    },
    {
        "type": "recipe",
        "name": "logistic-chest-storage",
        "enabled": False,
        "ingredients": {
            "steel-chest": 1,
            "electronic-circuit": 3,
            "advanced-circuit": 1,
        },
        "result": "logistic-chest-storage",
    },
    {
        "type": "recipe",
        "name": "logistic-chest-buffer",
        "enabled": False,
        "ingredients": {
            "steel-chest": 1,
            "electronic-circuit": 3,
            "advanced-circuit": 1,
        },
        "result": "logistic-chest-buffer",
    },
    {
        "type": "recipe",
        "name": "logistic-chest-requester",
        "enabled": False,
        "ingredients": {
            "steel-chest": 1,
            "electronic-circuit": 3,
            "advanced-circuit": 1,
        },
        "result": "logistic-chest-requester",
    },
    {
        "type": "recipe",
        "name": "rocket-silo",
        "enabled": False,
        "ingredients": {
            "steel-plate": 1000,
            "concrete": 1000,
            "pipe": 100,
            "processing-unit": 200,
            "electric-engine-unit": 200,
        },
        "energy_required": 30,
        "result": "rocket-silo",
        "requester_paste_multiplier": 1,
    },
    {
        "type": "recipe",
        "name": "roboport",
        "enabled": False,
        "energy_required": 5,
        "ingredients": {
            "steel-plate": 45,
            "iron-gear-wheel": 45,
            "advanced-circuit": 45,
        },
        "result": "roboport",
    },
    {
        "type": "recipe",
        "name": "substation",
        "enabled": False,
        "ingredients": {"steel-plate": 10, "advanced-circuit": 5, "copper-plate": 5},
        "result": "substation",
    },
    {
        "type": "recipe",
        "name": "accumulator",
        "energy_required": 10,
        "enabled": False,
        "ingredients": {"iron-plate": 2, "battery": 5},
        "result": "accumulator",
    },
    {
        "type": "recipe",
        "name": "electric-furnace",
        "ingredients": {"steel-plate": 10, "advanced-circuit": 5, "stone-brick": 10},
        "result": "electric-furnace",
        "energy_required": 5,
        "enabled": False,
    },
    {
        "type": "recipe",
        "name": "beacon",
        "enabled": False,
        "energy_required": 15,
        "ingredients": {
            "electronic-circuit": 20,
            "advanced-circuit": 20,
            "steel-plate": 10,
            "copper-cable": 10,
        },
        "result": "beacon",
    },
    {
        "type": "recipe",
        "name": "pumpjack",
        "energy_required": 5,
        "ingredients": {
            "steel-plate": 5,
            "iron-gear-wheel": 10,
            "electronic-circuit": 5,
            "pipe": 10,
        },
        "result": "pumpjack",
        "enabled": False,
    },
    {
        "type": "recipe",
        "name": "oil-refinery",
        "energy_required": 8,
        "ingredients": {
            "steel-plate": 15,
            "iron-gear-wheel": 10,
            "stone-brick": 10,
            "electronic-circuit": 10,
            "pipe": 10,
        },
        "result": "oil-refinery",
        "enabled": False,
    },
    {
        "type": "recipe",
        "name": "engine-unit",
        "energy_required": 10,
        "category": "advanced-crafting",
        "ingredients": {"steel-plate": 1, "iron-gear-wheel": 1, "pipe": 2},
        "result": "engine-unit",
        "enabled": False,
    },
    {
        "type": "recipe",
        "name": "electric-engine-unit",
        "category": "crafting-with-fluid",
        "energy_required": 10,
        "ingredients": {"engine-unit": 1, "lubricant": 15, "electronic-circuit": 2},
        "result": "electric-engine-unit",
        "enabled": False,
    },
    {
        "type": "recipe",
        "name": "flying-robot-frame",
        "energy_required": 20,
        "ingredients": {
            "electric-engine-unit": 1,
            "battery": 2,
            "steel-plate": 1,
            "electronic-circuit": 3,
        },
        "result": "flying-robot-frame",
        "enabled": False,
    },
    {
        "type": "recipe",
        "name": "explosives",
        "category": "chemistry",
        "normal": {
            "energy_required": 4,
            "enabled": False,
            "ingredients": {"sulfur": 1, "coal": 1, "water": 10},
            "result_count": 2,
        },
        "expensive": {
            "energy_required": 5,
            "enabled": False,
            "ingredients": {"sulfur": 2, "coal": 2, "water": 10},
            "result_count": 2,
        },
    },
    {
        "type": "recipe",
        "name": "battery",
        "category": "chemistry",
        "normal": {
            "energy_required": 4,
            "enabled": False,
            "ingredients": {"sulfuric-acid": 20, "iron-plate": 1, "copper-plate": 1},
            "result": "battery",
        },
        "expensive": {
            "energy_required": 5,
            "enabled": False,
            "ingredients": {"sulfuric-acid": 40, "iron-plate": 1, "copper-plate": 1},
            "result": "battery",
        },
    },
    {
        "type": "recipe",
        "name": "storage-tank",
        "energy_required": 3,
        "enabled": False,
        "ingredients": {"iron-plate": 20, "steel-plate": 5},
        "result": "storage-tank",
    },
    {
        "type": "recipe",
        "name": "pump",
        "energy_required": 2,
        "enabled": False,
        "ingredients": {"engine-unit": 1, "steel-plate": 1, "pipe": 1},
        "result": "pump",
    },
    {
        "type": "recipe",
        "name": "chemical-plant",
        "energy_required": 5,
        "enabled": False,
        "ingredients": {
            "steel-plate": 5,
            "iron-gear-wheel": 5,
            "electronic-circuit": 5,
            "pipe": 5,
        },
        "result": "chemical-plant",
    },
    {
        "type": "recipe",
        "name": "small-plane",
        "energy_required": 30,
        "enabled": False,
        "category": "crafting",
        "ingredients": {
            "plastic-bar": 100,
            "advanced-circuit": 200,
            "electric-engine-unit": 20,
            "battery": 100,
        },
        "result": "small-plane",
    },
    {
        "type": "recipe",
        "name": "arithmetic-combinator",
        "enabled": False,
        "ingredients": {"copper-cable": 5, "electronic-circuit": 5},
        "result": "arithmetic-combinator",
    },
    {
        "type": "recipe",
        "name": "decider-combinator",
        "enabled": False,
        "ingredients": {"copper-cable": 5, "electronic-circuit": 5},
        "result": "decider-combinator",
    },
    {
        "type": "recipe",
        "name": "constant-combinator",
        "enabled": False,
        "ingredients": {"copper-cable": 5, "electronic-circuit": 2},
        "result": "constant-combinator",
    },
    {
        "type": "recipe",
        "name": "power-switch",
        "enabled": False,
        "energy_required": 2,
        "ingredients": {"iron-plate": 5, "copper-cable": 5, "electronic-circuit": 2},
        "result": "power-switch",
    },
    {
        "type": "recipe",
        "name": "programmable-speaker",
        "enabled": False,
        "energy_required": 2,
        "ingredients": {
            "iron-plate": 3,
            "iron-stick": 4,
            "copper-cable": 5,
            "electronic-circuit": 4,
        },
        "result": "programmable-speaker",
    },
    {
        "type": "recipe",
        "name": "low-density-structure",
        "category": "crafting",
        "normal": {
            "energy_required": 20,
            "enabled": False,
            "ingredients": {"steel-plate": 2, "copper-plate": 20, "plastic-bar": 5},
            "result": "low-density-structure",
        },
        "expensive": {
            "energy_required": 20,
            "enabled": False,
            "ingredients": {"steel-plate": 2, "copper-plate": 20, "plastic-bar": 30},
            "result": "low-density-structure",
        },
    },
    {
        "type": "recipe",
        "name": "rocket-fuel",
        "energy_required": 30,
        "enabled": False,
        "category": "crafting-with-fluid",
        "ingredients": {"solid-fuel": 10, "light-oil": 10},
        "result": "rocket-fuel",
    },
    {
        "type": "recipe",
        "name": "rocket-control-unit",
        "energy_required": 30,
        "enabled": False,
        "category": "crafting",
        "ingredients": {"processing-unit": 1, "speed-module": 1},
        "result": "rocket-control-unit",
    },
    {
        "type": "recipe",
        "name": "rocket-part",
        "energy_required": 3,
        "enabled": False,
        "hidden": True,
        "category": "rocket-building",
        "ingredients": {
            "rocket-control-unit": 10,
            "low-density-structure": 10,
            "rocket-fuel": 10,
        },
        "result": "rocket-part",
    },
    {
        "type": "recipe",
        "name": "satellite",
        "energy_required": 5,
        "enabled": False,
        "category": "crafting",
        "ingredients": {
            "low-density-structure": 100,
            "solar-panel": 100,
            "accumulator": 100,
            "radar": 5,
            "processing-unit": 100,
            "rocket-fuel": 50,
        },
        "result": "satellite",
        "requester_paste_multiplier": 1,
    },
    {
        "type": "recipe",
        "name": "concrete",
        "energy_required": 10,
        "enabled": False,
        "category": "crafting-with-fluid",
        "ingredients": {"stone-brick": 5, "iron-ore": 1, "water": 100},
        "result": "concrete",
        "result_count": 10,
    },
    {
        "type": "recipe",
        "name": "hazard-concrete",
        "energy_required": 0.25,
        "enabled": False,
        "category": "crafting",
        "ingredients": {"concrete": 10},
        "result": "hazard-concrete",
        "result_count": 10,
    },
    {
        "type": "recipe",
        "name": "refined-concrete",
        "energy_required": 15,
        "enabled": False,
        "category": "crafting-with-fluid",
        "ingredients": {
            "concrete": 20,
            "iron-stick": 8,
            "steel-plate": 1,
            "water": 100,
        },
        "result": "refined-concrete",
        "result_count": 10,
    },
    {
        "type": "recipe",
        "name": "refined-hazard-concrete",
        "energy_required": 0.25,
        "enabled": False,
        "category": "crafting",
        "ingredients": {"refined-concrete": 10},
        "result": "refined-hazard-concrete",
        "result_count": 10,
    },
    {
        "type": "recipe",
        "name": "landfill",
        "energy_required": 0.5,
        "enabled": False,
        "category": "crafting",
        "ingredients": {"stone": 20},
        "result": "landfill",
        "result_count": 1,
    },
    {
        "type": "recipe",
        "name": "electric-energy-interface",
        "energy_required": 0.5,
        "enabled": False,
        "ingredients": {"iron-plate": 2, "electronic-circuit": 5},
        "result": "electric-energy-interface",
    },
    {
        "type": "recipe",
        "name": "nuclear-reactor",
        "energy_required": 8,
        "enabled": False,
        "ingredients": {
            "concrete": 500,
            "steel-plate": 500,
            "advanced-circuit": 500,
            "copper-plate": 500,
        },
        "result": "nuclear-reactor",
        "requester_paste_multiplier": 1,
    },
    {
        "type": "recipe",
        "name": "centrifuge",
        "energy_required": 4,
        "enabled": False,
        "ingredients": {
            "concrete": 100,
            "steel-plate": 50,
            "advanced-circuit": 100,
            "iron-gear-wheel": 100,
        },
        "result": "centrifuge",
    },
    {
        "type": "recipe",
        "name": "uranium-processing",
        "energy_required": 12,
        "enabled": False,
        "category": "centrifuging",
        "ingredients": {"uranium-ore": 10},
        "subgroup": "raw-material",
        "order": "k[uranium-processing]",
        "results": [
            {"name": "uranium-235", "probability": 0.007},
            {"name": "uranium-238", "probability": 0.993},
        ],
    },
    {
        "type": "recipe",
        "name": "kovarex-enrichment-process",
        "energy_required": 60,
        "enabled": False,
        "category": "centrifuging",
        "ingredients": {"uranium-235": 40, "uranium-238": 5},
        "icon": "__base__/graphics/icons/kovarex-enrichment-process.png",
        "icon_size": 32,
        "subgroup": "intermediate-product",
        "order": "r[uranium-processing]-c[kovarex-enrichment-process]",
        "main_product": "",
        "results": {"uranium-235": 41, "uranium-238": 2},
        "allow_decomposition": False,
    },
    {
        "type": "recipe",
        "name": "nuclear-fuel",
        "energy_required": 90,
        "enabled": False,
        "category": "centrifuging",
        "ingredients": {"uranium-235": 1, "rocket-fuel": 1},
        "icon": "__base__/graphics/icons/nuclear-fuel.png",
        "icon_size": 32,
        "result": "nuclear-fuel",
    },
    {
        "type": "recipe",
        "name": "nuclear-fuel-reprocessing",
        "energy_required": 60,
        "enabled": False,
        "category": "centrifuging",
        "ingredients": {"used-up-uranium-fuel-cell": 5},
        "icon": "__base__/graphics/icons/nuclear-fuel-reprocessing.png",
        "icon_size": 32,
        "subgroup": "intermediate-product",
        "order": "r[uranium-processing]-b[nuclear-fuel-reprocessing]",
        "main_product": "",
        "results": {"uranium-238": 3},
        "allow_decomposition": False,
    },
    {
        "type": "recipe",
        "name": "uranium-fuel-cell",
        "energy_required": 10,
        "enabled": False,
        "ingredients": {"iron-plate": 10, "uranium-235": 1, "uranium-238": 19},
        "result": "uranium-fuel-cell",
        "result_count": 10,
    },
    {
        "type": "recipe",
        "name": "heat-exchanger",
        "energy_required": 3,
        "enabled": False,
        "ingredients": {"steel-plate": 10, "copper-plate": 100, "pipe": 10},
        "result": "heat-exchanger",
    },
    {
        "type": "recipe",
        "name": "heat-pipe",
        "energy_required": 1,
        "enabled": False,
        "ingredients": {"steel-plate": 10, "copper-plate": 20},
        "result": "heat-pipe",
    },
    {
        "type": "recipe",
        "name": "steam-turbine",
        "enabled": False,
        "energy_required": 3,
        "ingredients": {"iron-gear-wheel": 50, "copper-plate": 50, "pipe": 20},
        "result": "steam-turbine",
    },
]
